### ISSUE TITLE
Source_Control_xx_Showing

### ISSUE THREAD

**Issue by ironcross13** [adelyte/crescendo#29]
In the latest builds the Source_Control_xx_Showing signal does not stay high after source is selected.  In the Touchscreen module_T_Page_Source_View is not staying high so the Showing buffer (3.2.3.4) is disabling and breaking the link to the interlock.  Was this an intended design change?

The ability to choose whether it as pulsed or asserted as in a few iterations back was nice.  The pulse does not work well with non SmartGraphics panels when setting screens via join.

**Comment by adelyte-austin** [comment]
The Pulse/Assert parameter was intentionally removed when the design decision to create source/device pages, rather than subpages, was made. A digital pulse to drive the page should work equally well for non-smart graphics panels however. It is advised to use the page method for all Guis for maximum compatibility.
Ideally the touchscreen page drive signals would assert / re-assert when selecting a same source. In testing this had unintended consequences, which is why the parameter and supporting logic was removed in version 2.0. This will be re-evaluated in a 2.1 version.

**Comment by adelyte-austin** [comment]
The performance from pulsing page control joins has yielded the best results with Crescendo UIs.
