### ISSUE TITLE
Slider on Lights Keypad module

### ISSUE THREAD

**Issue by ydelaune** [adelyte/crescendo#43]
Hello.

First of all congratulations for this great framework, is fantastic!

I have play around and I fill in the light keypad module an option to show sliders bellow corresponding buttons. If button doesn’t need slider it will not appear.

Slider works fine and send value to its corresponding load, but I found that if send a value touching the slider then I select another room the slider locate in the same position it sends the same value to the load assigned.

Seems that crosspoint is not disconnecting analog values as digital press and feedback works correctly.

any idea?

**Comment by adelyte-chris** [comment]
Yes, this is an issue with crosspoint routing we call "stale analogs". The problem is that crosspoint routing symbols work like Analog Buffers (not Serial Buffers). Analog Buffers propagate their values on the rising edge of the `enable` input. Likewise, crosspoint routing symbols propagate their values when they connect. (Serial Buffers do not propagate their values on the rising edge of `enable` but only on subsequent changes to their values.)

Serial signals are transient unless they are made permanent, which means they do not propagate when a new crosspoint connection is made. Therefore, the solution is to use analog signals only for state and use serial signals to trigger events. In this case, the "state" is the brightness of the lighting load and the "event" is sliding the slider to a new value. We have prior art you can reference within the `Touchscreen` module at `S-4.1.2` and especially the Analog to Serial at `S-4.1.2.6`. You can follow the signal

If you would like to post your code, we can provide you with specific guidance.

**Comment by ydelaune** [comment]
Hi Chris

Thanks for your feedback.

Yes, this is what i think that was happening. I also try to use serial buffer to send my slider level value but I have the same issue.

Maybe you can give me any advice.

I have attached the code, but don’t trust much on it
[Lights Keypad [Slider].zip](https://github.com/adelyte/crescendo/files/598453/Lights.Keypad.Slider.zip)

**Comment by adelyte-austin** [comment]
@ydelaune I reviewed your changes to the Lights Keypad module. Neither buffer type on the equipment side will prevent stale slider positions from propagating to the newly selected keypad. I will provide a code example that demonstrates how you can make this feature work inside the framework.

**Comment by ydelaune** [comment]
Hi Austin.

Thanks for your reply.

i have work around and found that i cab use the the digital join on the slider to enable an analog buffer, that will prevent "analog state" when changing betwen rooms.

it works but slider is not smooth as it should be

**Comment by marlonrac** [comment]
Hi, I'm starting to use the framework, I'm having the same problem with analog light control, any help will be welcome, thanks and congratulations for the work!
