### ISSUE TITLE
TSR-302 Lighting & Climate pages

### ISSUE THREAD

**Issue by DR7** [adelyte/crescendo#74]
Hello, I noticed when first loaded the TSR-302 that the lighting and climate pages did not appear, I uncommented feedback joins 13-15 that those pages and the rooms pages can now be accessed but another problem appears.

No device controller for climate and lighting appeared in the TSR-302 folder so I copied from another Touchscreen and set the right ID and changed my signal names but now have many errors because the TSR-302 does not use SG Objects so I have nowhere to route all the signals from the "Lighting device controller" and I get all these errors https://pastebin.com/tSWsWC5L

Where should a person be routing all these signals? Or perhaps I am not supposed to use the Light and Climate Device controllers for the TSR-302? Thanks for any info resolving this.

**Comment by adelyte-austin** [comment]
Currently, the TSR-302 does not feature global lighting and climate device access. Room defaults are selected using simple device routes on a `SerialIO` symbol.

Signals from the Device Controller modules connect to the subpage reference list extensions (See iPad programming). These UI elements do not exist in the TSR-302 graphics file, which is why the signals from your newly copied modules have no destination. To enable global device access on this remote, the SRLs must be added to the vtp, using the same joins as the iPad, and the SGD extensions synced and programmed in SIMPL Windows.

**Comment by DR7** [comment]
Thanks for the confirmation and detailed explanation, this helps a lot.

**Comment by adelyte-austin** [comment]
You're welcome @DR7. All of the objects and joins will mirror the full interfaces. Let us know if you run into issues.
