### ISSUE TITLE
iPhone TP - DVR Main CH Up/Down on same join

### ISSUE THREAD

**Issue by ryanww** [adelyte/crescendo#81]
Hey,

I noticed on the iPhone app file that on the page "[Source] [DVR] 1-MAIN" Both the channel up & down are set to join 333. 332 should be up, 333 should be down.

**Comment by adelyte-chris** [comment]
Nice catch. Would you like to submit a patch or have us fix it?

**Comment by DR7** [comment]
Chris I have to ask, somewhat of a git newb and I usually just download the code and work on my stuff and upload to another repo I have on Dreamhost for backups but if someone noticed something like this and wanted to submit a patch do they just clone a fresh copy of the crescendo repo and make a fork with that patch and then later Adelyte is notified of the patch and merges that with your repository? I've never really seen any sort of guide of doing this with Crestron code but have seen people mention not to add archives and some other file types so that's why I ask..thanks.

**Comment by adelyte-chris** [comment]
Sorry, I missed this reply. We use Git and GitHub/GitLab as part of our standard business workflow for every project, so it's easy to forget that other people have different workflows.

To submit a patch:
  1. [Fork this repository](https://help.github.com/articles/fork-a-repo/) and clone the forked repo to your local machine.
  2. Make the minimum number of changes required. In this case, modify the iPhone graphics file with the correct join.
  3. Commit those changes. In this case, `git commit -am "Fixed channel up join in iPhone graphics."` or something similar. If you use GUI tool rather than command line, the process is similar.
  4. Push those changes. In this case, `git push`. If you need to set the upstream branch, follow the instructions in the error message and [see StackOverflow for several options](https://stackoverflow.com/questions/6089294/why-do-i-need-to-do-set-upstream-all-the-time#6089415).
  5. Submit a [pull request](https://help.github.com/articles/about-pull-requests/).

**Comment by adelyte-chris** [comment]
@adelyte-austin Would you address this bug as soon as possible?

**Comment by DR7** [comment]
Thanks for the info Chris, appreciated!
