### ISSUE TITLE
Video zones that share switchers (TVs)

### ISSUE THREAD

**Issue by etechy** [adelyte/crescendo#82]
Imagine a commercial place with several TV sets in different areas and video walls.
I created several video zones e.g.:
1- All the TV sets that are not part of a video wall
2- Zone1: One halve of those TV sets
3- Zone2: The other halve
My first issues is that if I start by selecting All TVs, then just by selecting Zone1 it turns off those TVs, when I select a source it turns them back on and show that source.

I would rather like just by selecting zones it leaves the TVs on, showing the previously selected until the user selects a source or change his mind and go back to another zone without selecting.
Before attempting to trace why this is happening I would like to know about the reason of this behavior or if changing it might affect another desired behavior.

**Comment by etechy** [comment]
In other words, zone1 and zone2 are subsets of All TVs, which could be called complex or virtual room.
For the sake of communication I took the loft and added a FamilyKitchen room. Using the debugger can see the same is happening.

**Comment by adelyte-chris** [comment]
Rooms with shared displays, rooms with multiple displays, and video walls can all be tricky in Crescendo and usually require some extra logic:
  - _Rooms with shared displays_ sometimes require an `OR` outside the `Room` modules in order to get the proper power feedback for both rooms. This depends on the type of feedback desired (on if any, on if all, etc), and there is no right answer.
  - _Rooms with multiple displays_ require an extra navigation step to select the display, which in turn requires an expanded version of the `Touchpanel` module able to make direct connections to displays. We do not ship this version of `Touchpanel` since it's rarely sufficient for video walls.
  - _Video walls_ should be treated as standalone features with logic managed in SIMPL+ or SIMPL#. Trying to manage state for multiple displays and sources using SIMPL symbols is cumbersome and error prone.

Without looking at your code, I can only guess as to why switching from one zone to another is turning televisions off. In my experience, strange behavior when switching rooms (changing crosspoint routes) is almost always due to "stale" digital or analog values in `Touchpanel`. You might also have discovered a latent bug.

If you post a code archive, I would be happy to take a quick look and see if there are any obvious problems.

**Comment by etechy** [comment]
I think the feedback is a more complex issue that might even require an 'undefined' option because if we change the source of some of the TVs that are a subset of a previously used zone, the source for that bigger zone is no longer true or real.

The 'power off' issue can be seen in 'the loft' just by adding a FamilyKitchen (virtual) room.
E.g. if we first select the FamilyKitchen but no source, no power is triggered then go back and just select Kitchen or Family and back to FamilyKitchen and no power is triggered.

Once a source is selected for the FamilyKitchen, when just selecting Family or Kitchen it triggers a power off for any of them.
From my point of view this is unnecessary and undesirable, it seems to me an approach could be passing some action to happen when source selection, but I wonder if that could affect something else.

Thanks

**Comment by etechy** [comment]
Oh, had not seen the Austin commit, tried and no more power-off
Thanks
