### ISSUE TITLE
What join .do you use for DVR F1-F10?

### ISSUE THREAD

**Issue by bryanemerson** [adelyte/crescendo#88]
How would one figure this out?

**Comment by adelyte-austin** [comment]
If you look inside `Source.umc` you'll see the `F1 - F10` signals are `351 - 360` on the `ecross` symbol, which is referred to as the "output". This means a connected `ccross` must have those signals defined on the "input" side in the same positions.

These controls were originally created for the ML-600 soft keys and never made it onto the Touchscreen module. If you'd like to utilize them you'll need to open `Touchscreen.umc` and add the signals — I've attached a picture as a guide. There is an intentional gap after the named source controls so you will be able to define the signals @ `351 - 360` on your interfaces.

I will make a note to include this in a future release @bryanemerson.
<img width="1440" alt="touchscreen_functions_joins" src="https://user-images.githubusercontent.com/2684605/40279431-7ff28e76-5c10-11e8-8128-2edb06192f3c.png">
